username = input('Enter your name: ')
print('Name:', username)
title = input('Enter the note title: ')
print('Title name:', title)
content = input('Enter description: ')
print('Description:', content)
status = input ('Enter status of your note: ')
print('Status:', status)
created_date = input ('Enter the date of creation in the format dd-mm-yy:')
print('Date of creation: ', created_date)
issue_date = input('Enter deadline in format dd-mm-yy:')
print('Deadline: ', issue_date)